blank_issues_enabled: true
contact_links:
  - name: Community forum
    url: https://join.slack.com/t/wiremock-community/shared_invite/zt-1mkbo0zlx-gxeZdTJ15Kchdt888Fn_1A
    about: "You can discuss any ideas on Slack, in #general or another relevant channel"

